version: "3"
services:
  app:
    container_name: cardapio_api
    image: node:12
    ports:
      - "3333:3333"
    networks:
      - cardapio
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: sh -c "npm i && npm run start"
    environment:
      NODE_ENV: development
  # client:
  #   container_name: cardapio_client
  #   image: node:10
  #   networks:
  #     - cardapio
  #   ports:
  #     - "3000:3000"
  #   command: sh -c "npm i && npm run start"
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     NODE_ENV: development
networks:
  cardapio:
