version: "3"
services:
  app:
    container_name: cardapio_api
    image: node:alpine
    ports:
      - "8090:8090"
    networks:
      - cardapio
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: sh -c "npm i && npm run start"
    environment:
      NODE_ENV: development
    # depends_on:
    #   - fila
  # fila:
  #   container_name: cardapio_fila
  #   image: redis:alpine
  #   networks:
  #     - cardapio
  # client:
  #   container_name: cardapio_client
  #   image: node:alpine
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - cardapio
  #   volumes:
  #     - ./frontend:/frontend
  #   working_dir: /frontend
  #   command: sh -c "npm i && npm run start"
  #   environment:
  #     NODE_ENV: development
  #stdin_open: true
networks:
  cardapio:
